version: '3.7'

services:
  backend:
    restart: always
    container_name: backend
    build: ./backend
    volumes:
      - .:/opt
    ports:
      - 8080:8080

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    depends_on:
      - backend